# -*- coding: utf-8 -*-
"""generative_ai_smartbridge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njX20R4TJ_-Vr61fjGBtc6jj5_jTu8gY
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit

!streamlit --version

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Health-AI-main/

!pip install -r "/content/drive/MyDrive/Health-AI-main/requirements.txt"

import os

with open("/content/drive/MyDrive/Health-AI-main/env2.txt") as f:
    for line in f:
        if "=" in line:   # skip empty/comment lines
            key, value = line.strip().split("=", 1)
            os.environ[key] = value

os.getenv("IBM_WATSON_ML_API_KEY")

!pip install streamlit pyngrok

!streamlit run app.py &>/dev/null&

!ngrok authtoken 32KUgcHGkrfBs69nJ31vn3MRAmZ_52NnA4xvPe5g3Sm1L4B7m

from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("✅ Your Streamlit app is live here:", public_url)

